spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ecommerce?createDatabaseIfNotExist=true
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: TRUE
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: never
  mvc:
    hiddenmethod:
      filter:
        enabled: true

logging:
  level:
    org.springframework: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor: TRACE
    org.hibernate.orm.jdbc.bind: TRACE
    org.springframework.security: TRACE


jwt:
  secret: ${JWT_SECRET:}

app:
  client:
    url: http://localhost:4200/login

admin:
  name: "admin"
  email: "admin@email.com"
  password: ${ADMIN_PASS:}
